# Generated by Django 2.2.3 on 2019-07-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
