# Generated by Django 2.2.3 on 2019-08-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
