# Generated by Django 2.2.3 on 2019-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_auto_20190801_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
