# Generated by Django 2.2.3 on 2019-07-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190730_0742'),
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryDetail',
            new_name='InventoryItem',
        ),
    ]
