# Generated by Django 2.2.3 on 2019-08-02 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_is_delete'),
        ('sales', '0004_sale_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('archieved', 'Archieved'), ('cancel', 'Cancel')], default='open', max_length=100),
        ),
        migrations.DeleteModel(
            name='CustomerSale',
        ),
    ]
