# Generated by Django 2.2.3 on 2019-08-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20190803_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
