# Generated by Django 2.2.3 on 2019-08-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_saleitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='note',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='total',
        ),
    ]
