# Generated by Django 2.2.3 on 2019-08-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20190805_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
