# Generated by Django 2.2.3 on 2019-08-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20190805_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
