# Generated by Django 2.2.3 on 2019-08-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_saleitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
