# Generated by Django 2.2.3 on 2019-08-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20190805_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='verify_stock',
            field=models.BooleanField(default=False),
        ),
    ]
