# Generated by Django 2.2.3 on 2019-08-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_saleitem_verify_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='verify_stock',
        ),
    ]
