# Generated by Django 2.2.3 on 2019-08-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_remove_saleitem_verify_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
