# Generated by Django 2.2.3 on 2019-08-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20190807_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='total',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
