# Generated by Django 2.2.3 on 2019-08-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20190808_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='note',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.CharField(choices=[('BCA', 'BCA'), ('MANDIRI', 'MANDIRI'), ('BNI', 'BNI'), ('BTN', 'BTN'), ('BRI', 'BRI'), ('Cimb Niaga', 'Cimb Niaga')], default='BCA', max_length=100),
        ),
    ]
