# Generated by Django 2.2.3 on 2019-08-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20190808_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank',
        ),
    ]
