# Generated by Django 2.2.3 on 2019-08-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_remove_payment_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='is_percent',
            field=models.BooleanField(default=False),
        ),
    ]
